name: PR-Test

on: [pull_request]

jobs:
  build:
    name: pr-test
    runs-on: ubuntu-latest
    container:
      image: ucbbar/chisel3-tools
      options: --user github --entrypoint /bin/bash
    env:
      CONTAINER_HOME: /home/github

    steps:
      - name: id
        run: |
          whoami
          printenv
          git --version
          pwd
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Cache Scala
        uses: coursier/cache-action@v5
      - name: id2
        run: |
          whoami
          ls ~/.sbt
          printenv
          git --version
          pwd
      - name: test
        id: test
        run: sbt +test
      - name: id3
        run: |
          whoami
          ls ~/.sbt
          printenv
          git --version
          pwd
